name: first_flame
description: StarterProject for Game Development with Flame & Flutter

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flame: ^1.1.1
  flutter_riverpod: ^1.0.3
  flame_audio: ^1.0.2
  responsive_framework: ^0.1.7
  shared_preferences: ^2.0.13
  flutter_launcher_icons: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter_icons:
  image_path: 'assets/images/icon.png'
  android: true
  ios: true
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/tasks/
    - assets/audio/music/
    - assets/audio/sfx/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
